# Default parameters

# Parameters for the dataset selection
dataset:
  # Source file name
  path2source: '../datasets'

# Specify format for the log outputs
logformat:
  filename:    msgs.log
  datefmt:     '%m-%d %H:%M:%S'
  file_format: '%(asctime)s %(levelname)-8s %(message)s'
  file_level:  INFO
  cons_level:  DEBUG
  cons_format: '%(levelname)-8s %(message)s'

# Parameter for the keyword-based document selector
keywords:
  # Weight of the title. A word in the title is equivalent to wt repetitions
  # of the word in the description.
  wt: 2 
  # Maximum number of documents to be selected.
  n_max: 2000
  # Minimum score. Only docs scored strictly above s_min are selected
  s_min: 1

# Parameter for the keyword-based document selector
topics:
  # Maximum number of documents to be selected.
  n_max: 2000
  # Minimum score. Only docs scored strictly above s_min are selected
  s_min: 0.2

# Parameters for the classifier
classifier:
  # Maximum ratio negative vs positive samples in the training set
  max_imbalance: 3
  # Maxumum number of documents in the training set.
  nmax: 400

# Parameters for the active learning (AL)
active_learning:
  # Number of docs to show each AL round
  n_docs: 5
